import type { RoleConfig, UserRole } from './types';

export const ROLE_CONFIGS: Record<UserRole, RoleConfig> = {
  super_admin: {
    id: 'super_admin',
    label: 'Super Admin',
    description: 'Accès total au système, y compris données financières et coûts IA',
    badgeVariant: 'default',
    badgeColor: 'bg-red-600 text-white',
    canViewFinancials: true,
    canViewIACosts: true,
    canManageUsers: true,
    canManageContent: true,
    canModerateForum: true,
    canManageSupport: true,
    canManageSettings: true,
    canManageTranslations: true,
    countryScope: 'all',
  },
  admin_pays: {
    id: 'admin_pays',
    label: 'Admin Pays',
    description: 'Gestion limitée à son pays assigné',
    badgeVariant: 'secondary',
    badgeColor: 'bg-blue-600 text-white',
    canViewFinancials: false,
    canViewIACosts: false,
    canManageUsers: true,
    canManageContent: true,
    canModerateForum: true,
    canManageSupport: true,
    canManageSettings: false,
    canManageTranslations: true,
    countryScope: 'assigned',
  },
  admin_contenu: {
    id: 'admin_contenu',
    label: 'Admin Contenu',
    description: 'Gestion du contenu pédagogique',
    badgeVariant: 'secondary',
    badgeColor: 'bg-emerald-600 text-white',
    canViewFinancials: false,
    canViewIACosts: false,
    canManageUsers: false,
    canManageContent: true,
    canModerateForum: false,
    canManageSupport: false,
    canManageSettings: false,
    canManageTranslations: false,
    countryScope: 'none',
  },
  enseignant: {
    id: 'enseignant',
    label: 'Enseignant',
    description: 'Soumission de contenu, périmètre établissement(s)/matières/classes',
    badgeVariant: 'outline',
    badgeColor: 'bg-violet-100 text-violet-800',
    canViewFinancials: false,
    canViewIACosts: false,
    canManageUsers: false,
    canManageContent: false,
    canModerateForum: false,
    canManageSupport: false,
    canManageSettings: false,
    canManageTranslations: false,
    countryScope: 'none',
  },
  moderateur: {
    id: 'moderateur',
    label: 'Modérateur',
    description: 'Modération du forum uniquement',
    badgeVariant: 'outline',
    badgeColor: 'bg-amber-100 text-amber-800',
    canViewFinancials: false,
    canViewIACosts: false,
    canManageUsers: false,
    canManageContent: false,
    canModerateForum: true,
    canManageSupport: false,
    canManageSettings: false,
    canManageTranslations: false,
    countryScope: 'none',
  },
  support: {
    id: 'support',
    label: 'Support',
    description: 'Gestion des tickets et consultation limitée',
    badgeVariant: 'outline',
    badgeColor: 'bg-cyan-100 text-cyan-800',
    canViewFinancials: false,
    canViewIACosts: false,
    canManageUsers: false,
    canManageContent: false,
    canModerateForum: false,
    canManageSupport: true,
    canManageSettings: false,
    canManageTranslations: false,
    countryScope: 'none',
  },
  traducteur: {
    id: 'traducteur',
    label: 'Traducteur',
    description: 'Gestion des traductions de contenu',
    badgeVariant: 'outline',
    badgeColor: 'bg-pink-100 text-pink-800',
    canViewFinancials: false,
    canViewIACosts: false,
    canManageUsers: false,
    canManageContent: false,
    canModerateForum: false,
    canManageSupport: false,
    canManageSettings: false,
    canManageTranslations: true,
    countryScope: 'none',
  },
  validateur: {
    id: 'validateur',
    label: 'Validateur',
    description: 'Validation des traductions de contenu',
    badgeVariant: 'outline',
    badgeColor: 'bg-teal-100 text-teal-800',
    canViewFinancials: false,
    canViewIACosts: false,
    canManageUsers: false,
    canManageContent: false,
    canModerateForum: false,
    canManageSupport: false,
    canManageSettings: false,
    canManageTranslations: true,
    countryScope: 'none',
  },
};

export const ROLE_LABELS: Record<UserRole, string> = {
  super_admin: 'Super Admin',
  admin_pays: 'Admin Pays',
  admin_contenu: 'Admin Contenu',
  enseignant: 'Enseignant',
  moderateur: 'Modérateur',
  support: 'Support',
  traducteur: 'Traducteur',
  validateur: 'Validateur',
};

export const ROLE_COLORS: Record<UserRole, string> = {
  super_admin: 'bg-red-100 text-red-800 border-red-200 dark:bg-red-900/30 dark:text-red-400 dark:border-red-900/50',
  admin_pays: 'bg-blue-100 text-blue-800 border-blue-200 dark:bg-blue-900/30 dark:text-blue-400 dark:border-blue-900/50',
  admin_contenu: 'bg-emerald-100 text-emerald-800 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-400 dark:border-emerald-900/50',
  enseignant: 'bg-violet-100 text-violet-800 border-violet-200 dark:bg-violet-900/30 dark:text-violet-400 dark:border-violet-900/50',
  moderateur: 'bg-amber-100 text-amber-800 border-amber-200 dark:bg-amber-900/30 dark:text-amber-400 dark:border-amber-900/50',
  support: 'bg-cyan-100 text-cyan-800 border-cyan-200 dark:bg-cyan-900/30 dark:text-cyan-400 dark:border-cyan-900/50',
  traducteur: 'bg-pink-100 text-pink-800 border-pink-200 dark:bg-pink-900/30 dark:text-pink-400 dark:border-pink-900/50',
  validateur: 'bg-teal-100 text-teal-800 border-teal-200 dark:bg-teal-900/30 dark:text-teal-400 dark:border-teal-900/50',
};
